import React from 'react';
import { useTranslation } from 'react-i18next';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  Bell, 
  Trash2, 
  AlertTriangle, 
  AlertCircle, 
  CheckCircle2, 
  Info,
  Download,
  ToggleLeft,
  ToggleRight
} from 'lucide-react';
import { useSensors } from '../context/SensorContext';
import { StatusBadge } from '../components/Common';

const AlertsLogs: React.FC = () => {
  const { t } = useTranslation();
  const { 
    alerts, 
    logs, 
    pushNotifications, 
    setPushNotifications, 
    emailAlerts, 
    setEmailAlerts 
  } = useSensors();

  const handleDownloadReport = () => {
    try {
      const doc = new jsPDF();
      const date = new Date().toLocaleDateString();

      // --- Header & Branding ---
      doc.setFillColor(0, 115, 230); // BlueRoot Primary Blue
      doc.rect(0, 0, 210, 45, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(26);
      doc.setFont('helvetica', 'bold');
      doc.text('BlueRoot', 15, 28);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('SMART FARM OS - PERFORMANCE ANALYTICS', 15, 37);
      
      doc.text(`REPORT ID: BR-${Math.floor(Math.random() * 100000)}`, 150, 20);
      doc.text(`DATE: ${date}`, 150, 27);
      doc.text('STATUS: VERIFIED', 150, 34);

      // --- Section 1: Monthly Resource Analytics ---
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('1. Monthly Resource Analytics', 15, 65);
      
      const analyticsData = [
        ['Average Soil Moisture', '68.4%', '+2.1% from last month'],
        ['Water Consumption', '4,280 Liters', '-5% optimized'],
        ['Nutrient Utilization', '94.2%', 'High efficiency'],
        ['Average pH Level', '6.8 pH', 'Optimal'],
        ['System Response Time', '120ms', 'Excellent']
      ];

      autoTable(doc, {
        startY: 72,
        head: [['Resource Metric', 'Monthly Value', 'Performance Status']],
        body: analyticsData,
        theme: 'striped',
        headStyles: { fillColor: [0, 115, 230], fontSize: 11 },
        styles: { fontSize: 10, cellPadding: 4 }
      });

      // --- Section 2: System Health Summary ---
      const summaryY = (doc as any).lastAutoTable.finalY + 15;
      doc.setFontSize(18);
      doc.text('2. System Health Summary', 15, summaryY);
      
      const summaryData = [
        ['Total Critical Errors', alerts.filter(a => a.type === 'error').length],
        ['System Warnings', alerts.filter(a => a.type === 'warning').length],
        ['Informational Logs', alerts.filter(a => a.type === 'info').length],
        ['Automated Interventions', logs.length],
        ['Calculated Uptime', '99.98%']
      ];

      autoTable(doc, {
        startY: summaryY + 7,
        head: [['Metric Identifier', 'Value']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: [76, 175, 80], fontSize: 11 }, // Green
        styles: { fontSize: 10, cellPadding: 4 }
      });

      // --- Section 3: Recent Alerts & Faults ---
      doc.addPage();
      doc.setFontSize(18);
      doc.text('3. Detailed Alert Registry', 15, 25);
      
      const alertRows = alerts.map(a => [a.timestamp, a.type.toUpperCase(), a.message]);
      autoTable(doc, {
        startY: 32,
        head: [['Timestamp', 'Severity', 'Event Description']],
        body: alertRows.length > 0 ? alertRows : [['-', 'STABLE', 'No system faults detected in this period.']],
        theme: 'striped',
        headStyles: { fillColor: [0, 115, 230] },
        styles: { fontSize: 9 }
      });

      // --- Section 4: Operational Log ---
      const logY = (doc as any).lastAutoTable.finalY + 15;
      doc.setFontSize(18);
      doc.text('4. Operational Activity Log', 15, logY);
      
      const logRows = logs.map(l => [l.timestamp, l.type.toUpperCase(), `Motor triggered to ${l.action}`]);
      autoTable(doc, {
        startY: logY + 7,
        head: [['Execution Time', 'Component', 'Command Description']],
        body: logRows.length > 0 ? logRows : [['-', 'IDLE', 'No automated activities recorded.']],
        theme: 'grid',
        headStyles: { fillColor: [76, 175, 80] },
        styles: { fontSize: 9 }
      });

      // --- Footer ---
      const pageCount = (doc.internal as any).getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 120);
        doc.text(`BlueRoot SMART FARM OS - CONFIDENTIAL DATA | Generated by Automated Scheduler | Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
      }

      doc.save(`BlueRoot_Monthly_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error("PDF Generation failed:", error);
      alert("Failed to generate PDF. Please check the console.");
    }
  };

  const alertIconMap: Record<string, React.ReactNode> = {
    error: <AlertCircle size={20} />,
    warning: <AlertTriangle size={20} />,
    success: <CheckCircle2 size={20} />,
    info: <Info size={20} />,
  };

  const alertColorMap: Record<string, string> = {
    error: 'bg-red-50 dark:bg-red-500/10 text-red-500',
    warning: 'bg-amber-50 dark:bg-amber-500/10 text-amber-500',
    success: 'bg-green-50 dark:bg-[#1e9a4e]/10 text-[#1e9a4e]',
    info: 'bg-blue-50 dark:bg-blue-500/10 text-blue-500',
  };

  return (
    <div className="p-4 md:p-8 space-y-8 max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl md:text-3xl font-bold flex items-center gap-3 text-slate-800 dark:text-white">
            <Bell size={32} className="text-red-500 shrink-0" />
            {t('alerts.title')}
          </h2>
          <p className="text-slate-500 dark:text-white/40 font-medium">{t('alerts.subtitle')}</p>
        </div>

      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Alert List + Activity Log */}
        <div className="lg:col-span-2 space-y-6">
          {/* Alerts panel */}
          <div className="glass rounded-[1.5rem] md:rounded-[2rem] border border-[#1e9a4e]/40 shadow-[0_0_20px_rgba(30,154,78,0.15)] overflow-hidden">
            <div className="p-6 border-b border-slate-100 dark:border-white/5 flex items-center justify-between">
              <h3 className="font-bold text-slate-800 dark:text-white">{t('alerts.recentAlerts')}</h3>
              <button className="text-red-400 hover:bg-red-50 dark:hover:bg-red-500/10 p-2 rounded-lg transition-all">

                <Trash2 size={18} />
              </button>
            </div>
            <div className="divide-y divide-slate-50 dark:divide-white/5">
              {alerts.map((alert) => (
                <div key={alert.id} className="p-6 flex items-start gap-4 hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                  <div className={`p-3 rounded-2xl shrink-0 ${alertColorMap[alert.type] || alertColorMap.info}`}>
                    {alertIconMap[alert.type] || alertIconMap.info}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-1 gap-2">
                      <StatusBadge 
                        status={
                          alert.type === 'error' ? 'error' : 
                          alert.type === 'warning' ? 'warning' : 
                          alert.type === 'success' ? 'healthy' : 'active'
                        } 
                      />
                      <span className="text-xs font-medium text-slate-400 dark:text-white/40 whitespace-nowrap">{alert.timestamp}</span>
                    </div>
                    <p className="font-semibold text-sm text-slate-700 dark:text-white/80">{alert.message}</p>
                  </div>
                </div>
              ))}
              {alerts.length === 0 && (
                <div className="p-12 text-center text-slate-400 dark:text-white/40 font-medium">
                  {t('alerts.noActiveAlerts')}
                </div>
              )}

            </div>
          </div>

          {/* Activity Log */}
          <div className="glass rounded-[1.5rem] md:rounded-[2rem] border border-[#1e9a4e]/40 shadow-[0_0_20px_rgba(30,154,78,0.15)] overflow-hidden">
            <div className="p-6 border-b border-slate-100 dark:border-white/5">
              <h3 className="font-bold text-slate-800 dark:text-white">System Activity Log</h3>
            </div>
            <div className="p-6">
              <div className="space-y-4">
                {logs.map((log) => (
                  <div key={log.id} className="flex items-center gap-4 text-sm py-2 border-b border-slate-50 dark:border-white/5 last:border-0">
                    <div className="w-16 text-xs font-bold text-slate-400 dark:text-white/40 shrink-0">{log.timestamp.split(' ')[0]}</div>
                    <div className="flex-1 flex items-center gap-2 flex-wrap">
                      <span className={`w-2 h-2 rounded-full shrink-0 ${log.type === 'irrigation' ? 'bg-blue-500' : 'bg-purple-500'}`}></span>
                      <span className="font-bold uppercase tracking-wider text-[10px] text-slate-600 dark:text-white/60">{log.type === 'irrigation' ? t('nav.irrigation') : t('nav.fertigation')}</span>
                      <span className="text-slate-500 dark:text-white/60">{t('alerts.systemTriggered')}</span>
                      <span className={`font-bold ${log.action === 'START' ? 'text-[#1e9a4e]' : 'text-red-500'}`}>{log.action === 'START' ? t('fertigation.on') : t('fertigation.off')}</span>
                    </div>

                  </div>
                ))}
                {logs.length === 0 && (
                  <div className="text-center py-4 text-slate-400 dark:text-white/40 text-sm">No activity records yet.</div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Right sidebar */}
        <div className="space-y-6">
          {/* Report generation */}
          <div className="glass rounded-3xl p-6 border border-[#1e9a4e]/40 shadow-[0_0_20px_rgba(30,154,78,0.15)] bg-green-50/30 dark:bg-[#1e9a4e]/5">
            <h4 className="font-bold mb-4 flex items-center gap-2 text-slate-800 dark:text-white">
              <Download size={18} className="text-[#1e9a4e]" />
              {t('alerts.reportGeneration')}
            </h4>
            <p className="text-xs text-slate-500 dark:text-white/60 mb-6 leading-relaxed">
              {t('alerts.reportDesc')}
            </p>
            <button 
              onClick={handleDownloadReport}
              className="w-full py-3 rounded-xl bg-[#1e9a4e] text-white font-bold text-sm shadow-lg shadow-[#1e9a4e]/20 hover:bg-[#187a3e] transition-all"
            >
              {t('alerts.downloadReport')}
            </button>
          </div>

          <div className="glass rounded-3xl p-6 border border-[#1e9a4e]/40 shadow-[0_0_20px_rgba(30,154,78,0.15)]">
            <h4 className="font-bold mb-4 text-slate-800 dark:text-white">{t('alerts.notificationSettings')}</h4>
            <div className="space-y-4">
              {[
                { label: t('alerts.pushNotifications'), enabled: pushNotifications, toggle: () => setPushNotifications(!pushNotifications) },
                { label: t('alerts.emailAlerts'), enabled: emailAlerts, toggle: () => setEmailAlerts(!emailAlerts) },
              ].map((item) => (
                <div key={item.label} className="flex items-center justify-between py-2">
                  <span className="text-sm font-medium text-slate-600 dark:text-white/70">{item.label}</span>
                  <button onClick={item.toggle} className="focus:outline-none">
                    {item.enabled 
                      ? <ToggleRight size={28} className="text-[#1e9a4e]" />
                      : <ToggleLeft size={28} className="text-slate-300 dark:text-white/20" />
                    }
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Summary stats */}
          <div className="glass rounded-3xl p-6 border border-[#1e9a4e]/40 shadow-[0_0_20px_rgba(30,154,78,0.15)]">
            <h4 className="font-bold mb-4 text-slate-800 dark:text-white">{t('alerts.alertSummary')}</h4>
            <div className="space-y-3">
              {[
                { label: t('alerts.errors'), count: alerts.filter(a => a.type === 'error').length, color: 'text-red-500 bg-red-50 dark:bg-red-500/10' },
                { label: t('alerts.warnings'), count: alerts.filter(a => a.type === 'warning').length, color: 'text-amber-500 bg-amber-50 dark:bg-amber-500/10' },
                { label: t('alerts.info'), count: alerts.filter(a => a.type === 'info').length, color: 'text-blue-500 bg-blue-50 dark:bg-blue-500/10' },
                { label: t('alerts.resolved'), count: alerts.filter(a => a.type === 'success').length, color: 'text-[#1e9a4e] bg-green-50 dark:bg-[#1e9a4e]/10' },
              ].map((item) => (
                <div key={item.label} className="flex items-center justify-between">
                  <span className="text-sm text-slate-500 dark:text-white/60">{item.label}</span>
                  <span className={`text-xs font-black px-2 py-1 rounded-lg ${item.color}`}>{item.count}</span>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default AlertsLogs;
